name: Python application test with Github actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
    - uses: action/checkout@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Lint python
      run: |
        make lint
    - name: Test with Pytest
      run: |
        make test
    - name: format code black
      run: |
         make format
    
